### ISSUE TITLE
Composer conflict with magento 2.1.0

### ISSUE THREAD

**Issue by rhertogh** [vmasciotta/magento2-owl-carousel#2]
Hi,
Composer gives a conflict due to the "magento/module-ui": "100.0.*" requirement, magento 2.1 requires magento/module-ui 100.1.0
Is magento 2.1 support on the roadmap?

details:
`Problem 1
    - vmasciotta/magento2-owl-carousel 1.0.0 requires magento/module-ui 100.0.* -> satisfiable by magento/module-ui[100.0.5, 100.0.2, 100.0.3, 100.0.4].
    - vmasciotta/magento2-owl-carousel 1.0.0 requires magento/module-ui 100.0.* -> satisfiable by magento/module-ui[100.0.5, 100.0.2, 100.0.3, 100.0.4].
    - Can only install one of: magento/module-ui[100.1.0, 100.0.5].
    - Can only install one of: magento/module-ui[100.1.0, 100.0.2].
    - Can only install one of: magento/module-ui[100.1.0, 100.0.3].
    - Can only install one of: magento/module-ui[100.1.0, 100.0.4].
    - Can only install one of: magento/module-ui[100.1.0, 100.0.5].
    - magento/product-community-edition 2.1.0 requires magento/module-ui 100.1.0 -> satisfiable by magento/module-ui[100.1.0].
    - Installation request for magento/product-community-edition 2.1.0 -> satisfiable by magento/product-community-edition[2.1.0].
    - Installation request for vmasciotta/magento2-owl-carousel 1.0.0 -> satisfiable by vmasciotta/magento2-owl-carousel[1.0.0].
`

**Comment by vmasciotta** [comment]
Hi and thank You for your report.
I've updated the composer file. Can You try to install it now?

**Comment by rhertogh** [comment]
Looking good, thanks :+1:

**Comment by dipak85shinde** [comment]
Is this support for Magento 2.2.2?

I am getting error like **vmasciotta/magento2-owl-carousel 1.0.0 requires magento/module-ui 100.0.* -> satisfiable by magento/module-ui[100.0.2, 100.0.3, 100.0.4, 100.0.5, 100.0.6, 100.0.7, 100.0.8, 100.0.9, 100.0.10, 100.0.11, 100.0.12]**
