### ISSUE TITLE
Loading delay

### ISSUE THREAD

**Issue by davidgmarchand** [vmasciotta/magento2-owl-carousel#3]
Hi! I'm not sure if it's really an issue, but using both the methods in the docs there is a 1sec delay until the owl carousel actually loads. Do you know a way to fix this?

Thanks,

**Comment by vmasciotta** [comment]
Hi, I noticed this behavior too but I wasn't able to change it.
I'm gonna close this is issue because I consider it an "aesthetic" one. If You found out a way, I'm curious to know how U fixed it.

Thanks
