### ISSUE TITLE
Support for PHP 7.1 / Magento 2.2

### ISSUE THREAD

**Issue by phtmgt** [vmasciotta/magento2-owl-carousel#8]
Currently the module cannot be installed on such a config. Are there any plans to migrate any time soon?

Thanks.

**Comment by emil-777** [comment]
Are there any news regarding the 2.2 compatibilty?

**Comment by vmasciotta** [comment]
I'm gonna release a major update soon of this module with owl carousel 2.2.1 and a composer.json updated for magento 2.2.x

U can try it using the development branch version.

Master version is compatible with Magento 2.2.x too, don't use composer in that case and install it using zip package.
