### ISSUE TITLE
issue in magento 2.2.5

### ISSUE THREAD

**Issue by vrajeshpatel4u** [vmasciotta/magento2-owl-carousel#9]
i have installed magento 2.2.5 but all the images are displayed one by one not in slider. In earlier version it is working fine.

**Comment by vmasciotta** [comment]
Hi I'll check it as soon as I can

**Comment by vrajeshpatel4u** [comment]
Sure,Thank You Sir.

**Comment by vmasciotta** [comment]
Can you please try to install the dev-develop version then setup:upgrade, clean and flush cache?
It works fine on my environment.

**Comment by vrajeshpatel4u** [comment]
Not working. Same as earlier. All images in one line not in slider
